# Generated by Django 3.0 on 2020-06-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0002_remove_choice_is_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rounds', models.IntegerField(default=1)),
                ('ques_in_round', models.IntegerField(default=5)),
                ('questions', models.ManyToManyField(to='polls.Question')),
            ],
        ),
    ]
